In [1]:
import numpy as np

arr = [6, 7, 8, 9]
print(type(arr)) # prints <class 'list'>

a = np.array(arr)
print(type(a))  # prints <class 'numpy.ndarray'>
print(a.shape)  # prints (4,) - a is a 1d array with 4 items
print(a.dtype)  # prints int64

# get the dimension of a with ndim 
print(a.ndim)   # prints 1

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)        # prints [[1 2 3] [4 5 6]]
                         
print(b.ndim)   # prints 2
b.shape         # prints (2, 3) - b a 2d array with 2 rows and     3 columns

<class 'list'>
<class 'numpy.ndarray'>
(4,)
int32
1
[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [7]:
# a 2x3 array with random values
np.random.random((2, 3)) # a 2x3 array of zeros


array([[0.82244034, 0.95209597, 0.31644586],
       [0.7806477 , 0.32466368, 0.94277201]])

In [8]:
np.zeros((2, 3)) #= array([[0., 0., 0.],[0., 0., 0.]])
# a 2x3 array of ones

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2, 3)) #= array([[1., 1., 1.], [1., 1., 1.]])
# a 3x3 identity matrix 


array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((3, 3)) #= array([[1., 1., 1.], [1., 1., 1.]])
# a 3x3 identity matrix 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
a = np.zeros((2, 3))
print(a)
np.diag((2, 3)) #= array([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]])

[[0. 0. 0.]
 [0. 0. 0.]]


array([[2, 0],
       [0, 3]])

In [37]:
np.zeros((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [55]:
x = np.arange(9).reshape((3,3))

In [39]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [40]:
np.diag(x)

array([0, 4, 8])

In [42]:
x = np.zeros(3, 3)

In [47]:
x

array([0., 0., 0.])

In [51]:
np.eye(3) #= array([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])