In [6]:
import numpy as np
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

In [7]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [8]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [9]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])